stages:
  - build
  - deploy

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - _book

build:
  stage: build
  script:
    - gitbook install
    - gitbook build

deploy:
  stage: deploy
  only:
      - master
  script:
    - sh deploy.sh
  environment:
    name: mpx-docs
    url: http://10.96.94.162/mpx
